name: API pipeline
run-name: ${{github.actor}} is running CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run Linter
        run: pnpm lint

      - name: Run build
        run: pnpm build

      - name: Run unit-tests
        run: pnpm test

      - run: echo "💯 lint-and-unit job's status is ${{job.status}}"